### PR TITLE
Cache NUMBA kernels between CI runs

### LINKED ISSUE #278: Suggestion: Use github actions to cache numba kernels
# Describe the problem that the feature should address

Currently CI is taking an increasing amount of time to run because all numba kernels have to be compiled from scratch.

In conversation with @JSKenyon, it seems most, if not all kernels are decorated with `cache=True`. This implies that its not necessary to recompile kernels from scratch all the time.

# Describe the solution you'd like

Numba respects a [NUMBA_CACHE_DIR](https://numba.readthedocs.io/en/stable/reference/envvars.html#envvar-NUMBA_CACHE_DIR) variable, while github actions has access to [per-repository-caches](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows).

A github action cache key  can be constructed from shell/environment variables/hashing files and this is used to determine [cache hits/misses](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#cache-hits-and-misses). e.g. `numba-cache-abcdef1234567890`. However, I suspect that we don't really want to manage these hits and misses ourselves -- we really just want some path that we can point `NUMBA_CACHE_DIR` at and let numba handle individual kernel cache hits/misses according to it's internal logic.

If the above follows, then it should be sufficient to use a well structured key (i.e. prefixed with `numba-cache-`) in conjunction with the `actions/cache@v3` `restore-keys` to restore the most recent numba kernel cache and construct a new one during the current CI run. 

This should speed up CI runs to the degree that code changes propagate to all numba code -- a change fundamental to all numba kernels will recompile the entire code base, while a peripheral one might just change one kernel.

### PR DESCRIPTION
**Pull request by sjperkins**
Closes #278

### CODE REVIEW

**Comment by JSKenyon** [comment]
This looks awesome! I will probably move this to the dev branch before merging.

**Comment by sjperkins** [comment]
Hmmm, I was fairly sure I mkdir'd that

image

**Comment by sjperkins** [comment]
So the kernel caching does not seem to be improving the test suite run time. even though kernel caches are created: https://github.com/ratt-ru/QuartiCal/actions/caches. This would also seem to suggest NUMBA_CACHE_DIR is respected.

**Comment by JSKenyon** [comment]
> So the kernel caching does not seem to be improving the test suite run time. even though kernel caches are created: https://github.com/ratt-ru/QuartiCal/actions/caches. This would also seem to suggest NUMBA_CACHE_DIR is respected.

Is respected, or isn't? Might need to rerun the tests a few times - I have muddied the waters by merging in main. I do think that there is probably something which can be done - will take a closer look at the end of the week.

**Comment by sjperkins** [comment]
> > So the kernel caching does not seem to be improving the test suite run time. even though kernel caches are created: https://github.com/ratt-ru/QuartiCal/actions/caches. This would also seem to suggest NUMBA_CACHE_DIR is respected.
> 
> Is respected, or isn't?

I think it is respected -- The caches are about 11MB. 

Another thought occurred, the cached kernel modification times are probably earlier than the checked out python code -- this might trigger recompilation. This is just speculation on my part and the docs don't mention this at all: https://numba.readthedocs.io/en/stable/cuda/caching.html

**Comment by sjperkins** [comment]
> Another thought occurred, the cached kernel modification times are probably earlier than the checked out python code -- this might trigger recompilation: https://numba.readthedocs.io/en/stable/developer/caching.html
> 
> > The cache is invalidated when the corresponding source file is modified.

Unfortunately  it looks like it is the case that the timestamp is only the input to the cache key (at least as of Aug 22): https://numba.discourse.group/t/cache-behaviour/1520

> I would like to propose to move away from invalidating the cache index based on the timestamp of the file, and use only the code+closure signature of the function itself. Would anyone see a problem with that? When I say code+closure signature I mean the exact same information that is used to select the overload from within the cache.

So this approach doesn't seem viable.

**Comment by JSKenyon** [comment]
> So this approach doesn't seem viable.

Ah unfortunate. Perhaps there will be progress upstream at some point.

**Pull request merged**
